
spring:
  application:
    name: E-medcare
  datasource:
    url: jdbc:mysql://localhost:3306/e_medcare
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    database: mysql

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/e_medcare
    user: root
    password: ""
    schemas: e_medcare
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
