server:
  servlet:
    session:
      timeout: 60m

spring:
  application:
    name: sfm
  datasource:
    url: jdbc:postgresql://localhost:5432/E-MedCare
    username: postgres
    password: z6$Q432yl
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    database: postgresql

  flyway:
    schemas: public
    default-schema: public
    url: jdbc:postgresql://localhost:5432/E-MedCare
    user: postgres
    password: z6$Q432yl
    locations: classpath:db/migration
    enabled: true
    clean_on_startup: false
    baseline_on_migrate: true
    out-of-order: true
